import React from 'react';
import { PatientRecord } from '../types/chat';
import { Card, CardHeader, CardTitle, CardContent, CardFooter } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { User, MapPin, Activity, Calendar, Phone, Heart } from 'lucide-react';

interface HealthPassportProps {
  record: PatientRecord;
}

export const HealthPassport: React.FC<HealthPassportProps> = ({ record }) => {
  return (
    <Card className="w-full max-w-md mx-auto border-2 border-cyan-200 shadow-lg bg-white overflow-hidden">
      <div className="bg-cyan-600 p-4 text-white flex justify-between items-center">
        <div>
          <h2 className="text-xl font-bold">EdifexMed Health Passport</h2>
          <p className="text-xs opacity-90 font-medium uppercase tracking-wider">Official Rural Health Record</p>
        </div>
        <Heart className="text-white fill-white animate-pulse" size={24} />
      </div>
      
      <CardContent className="p-6 space-y-4">
        <div className="grid grid-cols-2 gap-4">
          <div className="space-y-1">
            <p className="text-[10px] text-muted-foreground uppercase font-semibold">Patient Name</p>
            <div className="flex items-center gap-2">
              <User size={16} className="text-cyan-600" />
              <p className="font-bold text-slate-800">{record.name || '---'}</p>
            </div>
          </div>
          <div className="space-y-1">
            <p className="text-[10px] text-muted-foreground uppercase font-semibold">Village</p>
            <div className="flex items-center gap-2">
              <MapPin size={16} className="text-cyan-600" />
              <p className="font-bold text-slate-800">{record.village || '---'}</p>
            </div>
          </div>
        </div>

        <div className="space-y-1 pt-2 border-t">
          <p className="text-[10px] text-muted-foreground uppercase font-semibold">Status</p>
          <div className="flex items-center gap-2">
            <Badge variant={record.maternalStatus === 'general' ? 'secondary' : 'default'} className="bg-emerald-100 text-emerald-800 border-emerald-200">
              {record.maternalStatus === 'general' ? 'General Patient' : record.maternalStatus === 'pregnant' ? 'Maternal Care' : 'Mother & Infant'}
            </Badge>
          </div>
        </div>

        <div className="space-y-1 pt-2 border-t">
          <p className="text-[10px] text-muted-foreground uppercase font-semibold">Reported Symptoms</p>
          <div className="flex items-start gap-2">
            <Activity size={16} className="text-red-500 mt-1 shrink-0" />
            <p className="text-sm italic text-slate-700 leading-relaxed">{record.symptoms || 'No symptoms reported'}</p>
          </div>
        </div>

        {record.bookingDetails && (
          <div className="space-y-1 pt-2 border-t">
            <p className="text-[10px] text-muted-foreground uppercase font-semibold">Clinic Appointment</p>
            <div className="bg-cyan-50 p-3 rounded-md border border-cyan-100">
              <div className="flex items-center gap-2 mb-1">
                <Calendar size={14} className="text-cyan-700" />
                <p className="text-sm font-bold text-cyan-900">
                  {record.bookingDetails.day}, {record.bookingDetails.time}
                </p>
              </div>
              <div className="flex items-center gap-2">
                <MapPin size={14} className="text-cyan-700" />
                <p className="text-xs text-cyan-800">{record.bookingDetails.location}</p>
              </div>
            </div>
          </div>
        )}

        {record.contactPhone && (
          <div className="space-y-1 pt-2 border-t">
            <p className="text-[10px] text-muted-foreground uppercase font-semibold">Contact Phone</p>
            <div className="flex items-center gap-2">
              <Phone size={14} className="text-cyan-600" />
              <p className="text-sm font-mono font-bold tracking-tighter text-slate-800">{record.contactPhone}</p>
            </div>
          </div>
        )}
      </CardContent>

      <CardFooter className="bg-slate-50 border-t p-4 flex flex-col items-center gap-2">
        <div className="w-24 h-24 bg-white border p-1 mb-1">
          {/* Simulated QR Code */}
          <div className="w-full h-full bg-[radial-gradient(circle_at_center,_#000_1px,_transparent_1px)] bg-[length:4px_4px] opacity-20"></div>
        </div>
        <p className="text-[10px] text-center text-muted-foreground">
          Show this card to the health worker upon arrival. <br />
          Generated by EdifexMed Rural Health Companion.
        </p>
      </CardFooter>
    </Card>
  );
};
